### ISSUE TITLE
Include Test Vectors

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/tbdex#169]
Test vectors will be super helpful w.r.t. interoperability across implementations. "Test vectors" sounds fancy but it’s really as simple as tossing a `test-vectors.json` file into this repo. Json structure could be something like:

```jsonc
{
    "resources": {
        "offering": [{ /* signed offering */ }]
    },
    "messages": {
        "rfq": [{ /* signed rfq */ }],
        "quote": [{ /* signed quote */ }],
        "order": [{ /* signed order */ }],
        "orderstatus": [{ /* signed orderstatus */ }],
        "close": [{ /* signed close */ }]

    }
}
```

any/all implementations can pull this into their tests, traverse the object, and for each resource or message:
* parse
* call sign to ensure that the same signature is generated

2nd one is a bit tricky because not all signature algorithms generate deterministic signatures (`secp256k1` does). We could just include a private key in the vector file

ideally, don't want to fall into a situation where we have this combinatorial matrix of each language's sdk generating its own vectors and also consuming the vectors of every other lib

**Comment by leordev** [comment]
Does it make sense to have a bunch of requests and expected responses for a given scenario? So the test can assert the responses?

Curious question: Why do we need to assert the signature equality? If we have enough unit tests to cover the signature generation, can't we just compare the expected response bodies ignoring the signature, and then just check if the signature in the response is valid regardless of its value?

**Comment by phoebe-lew** [comment]
@mistermoe I'm leaning towards having a provided input and some expected output, whether it's a successful output or an expected failure. Would have duplicative input for parse and sign, is that a big issue for you? Can you think of any other reasons to only provide the input and have the consumer of the vectors know to test both parsing and signing?

The original reason for providing input + output was so that test vector structure could be a bit more similar across web5 and tbdex vectors (for test harness consumption purposes), but lmk if you think that's a premature optimization!

Also for me personally, providing an object in the vector and then expecting the consumer to know what to do with it is a leeetle ambiguous. It's clearer to me (this could be subjective), if the vectors always state: "this is the thing i'm testing", "this is your input", "this should be the output"

**Comment by mistermoe** [comment]
@phoebe-lew is [this](https://github.com/TBD54566975/tbdex/blob/6f7759f345b6821fd32d19857197d04d11d03ba2/hosted/test-vectors/vector-structure.json) what you've got in mind? p.s. i think `testId`, and `description` are awesome ideas. 

no issue with duplication whatsoever! i imagine the code used to generate the test vectors won't be duplicative. 

for my initial stab, i started with including `output` but backed out because i wasn't sure how to reflect `output` when its an exception vs. value vs. nothing in a way that made no assumptions about api surfaces in different languages. but was also super strapped for time!
