### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/tbdex#172]
How should tbDEX be versioned? There's quite a bit to unpack. Here's a few more concrete questions:

* Do we version the entire protocol? What are the implications of doing so? what is the resulting outcome?
* are individual message / resource schemas versioned? or are they all versioned together? Is this _in addition_ to versioning the entire protocol or is it what _causes_ the protocol to be versioned?
* what versioning scheme would one even use?

## Examples

so wot types of stuff can change? 2 categories i think

### Protocol-wide
* adding a net new message kind to tbdex. hopefully rare. Contrary would lead to a bloated / confusing protocol
  * required or optional message? required would change the state machine of an exchange
* message / resource removal (idk what this would even look like)
* adding a new resource kind
  * required or optional resource?

### Schema specific
* adding a field to a resource or schema
  * required or optional? 
* removing a field
  * was the field required or optional?
* updating data type of existing field - e.g. `paymentDetails` goes from being an object to an array

## Random Thoughts
Goal should be to keep versioning as simple as possible. Versioning the protocol itself _and_ individual schemas seems like it could get complicated to keep up with - "oh yeah i talk version 2 of tbdex but only version 3 of rfq and quote but version 4 of order"

---

maybe `x.x` semantic versioning does make sense where:
- major version bump:
    - a breaking change. **_not_** backwards compatible e.g.
        - adding a new required message kind
        - adding a new required property to an existing message kind
        - removing existing required property
        - changing data type of exsting field
- minor version bump:
  - backwards compatible change e.g.
    - adding a new optional field to a message

probably need to think ^ through a bit more. write up a list of different types of changes.

also worth looking into prior art

---

## Pratical Application

Maybe proposals to make changes to tbDEX can happen by submitting _TIPs_ (e.g. tbDEX Improvement Proposal).

Need to figure out structure of a TIP and what stages a TIP goes through.

Rough thoughts - TIP remains a draft until it's implemented & in-use by _n_ PFIs / SDKs  

I think every version major or minor should have a full set of message/resource schemas. will just be easier to track that way.

## TODOs
* Look at prior art for schema versioning
* Look at prior art for `*IP`s e.g. BIP, BEP, EIP etc.
* Look at prior art for protocol versioning - http, tcp, amqp etc.
* Implementation #159

**Comment by mistermoe** [comment]
related: #159

**Comment by KendallWeihe** [comment]
Alright... so, here are my takes... 

- The [protocol spec](https://github.com/TBD54566975/tbdex/tree/main/specs/protocol) is the source of truth
  - Let's refer to everything else (JSON schemas, http-api, `tbdex-js`, `tbdex-kt`), which are downstream of the spec, as _"implementations"_
    - As an aside, there are three distinct abstractions within "implementations": schemas, transports, and languages but for the sake of simplicity here we can group them together
  - There's a tangential discussion around what the standard format of a "protocol spec" ought to conform to -- to which I would say, there is no standard format b/c otherwise it would be standards-all-the-way-down and that leaves no room for human creativity ... I digress
    - For now, in practice for tbDEX, this equates to the human-readable (& I guess now LLM-readable) [text file here](https://github.com/TBD54566975/tbdex/tree/main/specs/protocol)
- Spec is versioned as a whole, defined within the spec doc(s)
- Spec semantic versioning will be `{major}.{minor}`
- Implementation versions will 1:1 mirror spec version, with the addition of a `{patch}` to account for syntactical errors, security patches, etc. 👉 so that's `{major}.{minor}.{patch}`
- What constitutes a `major` vs `minor` is a matter of runtime compatibility
  - In this moment, the only change I can think of which constitutes a `minor` change would be **_adding_** _optional_ data
  - IMO this spans to both Message kind fields but also Resource & Message kinds themselves
    - Adding a new optional Message kind, which (by the definition of "optional") doesn't alter the semantic requirements of the protocol, doesn't break compatibility
    - The same is true for Resources
    - Change my mind ☕ 
- We should discuss what it means to derive version compatibility at runtime
  - Every communication at runtime ought to include the version
  - The language implementations must support the ability to read the version even if their runtime doesn't support the given version's data structure
    - For example, say a client only supports `3.4` but they download an `Offering` from a PFI which is versioned at `2.1`, then the client implementation should be able to derive that without throwing a deserialization error
    - The solution can be unique to the given transport implementation
      - For example, tbDEX over HTTP could use HTTP headers
- "TIP" = tbDEX Improvement Proposal: a place for open source to propose changes to the protocol ([example for bitcoin here](https://github.com/bitcoin/bips)) 👍 

I'm sure there are more matters to discuss, but feedback on these takes welcome!

**Comment by michaelneale** [comment]
building on kendalls thoughts: what does it mean when there is a new version of something: what client/server has to change, how often etc, how do things work with old client and new server and vice versa, or they just have to be all the latest version etc. I am mostly thinking about how the participants in tbdex update their bits. Its a bit ask to ask people in a distributed or decentralized network to update their stuff too often, so in a sense updating versions can be a "big deal" and need a "TIP" etc.

**Comment by KendallWeihe** [comment]
### HTTP API Versioning

Something which has come up in recent development... the need to version the [HTTP API](https://github.com/TBD54566975/tbdex/tree/main/specs/http-api). I suppose the easy solution is to add a path prefix, so for example `GET /v2.2/offerings` or `GET /v2.2/exchanges`

**Comment by michaelneale** [comment]
I have seen headers used to specify a version: https://docs.github.com/en/rest/overview/api-versions?apiVersion=2022-11-28

**Comment by KendallWeihe** [comment]
> I have seen headers used to specify a version: https://docs.github.com/en/rest/overview/api-versions?apiVersion=2022-11-28

Yeah I think this is slightly more aesthetically pleasing without any loss of clarity so I'm pro

**Comment by mahoekst** [comment]
On the versioning in the did doc of the PFI, We might need to discuss that seperately where there is a way for a PFI to let the network know what it supports. Could be API version X but also additional did methods, which currency or anything else which could be different sometime in the future.

**Comment by decentralgabe** [comment]
@mahoekst this should be profile driven IMO.

**Comment by mahoekst** [comment]
Not sure if everything fits in a profile. I can see why tbDEX 1.0 supports issuance profile preview bla and perhaps 2.0 the final version. If would be nice to understand what is supported by the PFI or not, including certain currencies?

Are we suggesting to create a tbDEX profile and version that? And have the PFI publish which profile they support? (one or more?)

**Comment by decentralgabe** [comment]
Version of the tbdex API should be in a profile (e.g. v1.0), there should be a generic INFO-style endpoint you can call as part of that profiled API to return currencies supported

**Comment by phoebe-lew** [comment]
Proposal: https://hackmd.io/TucOUP8UQt-XKj8G9UsJ2Q
