### ISSUE TITLE
Consider pulling in PaymentDetails as an optional field inside QuoteDetails in Quote

### ISSUE THREAD

**Issue by jiyoontbd** [TBD54566975/tbdex#201]
From @diehuxx 's comment on [discord](https://discord.com/channels/937858703112155166/949067728709369856/1182469791211069541)

> Is there any strong reason Quote has a payin and payout field with QuoteDetails and it has PaymentInstructions with a its payin and payout field? Is there a reason we didn't want to fold PaymentInstruction as an optional field in QuoteDetails? No push back, it seems like a small thing to me, but curious if there's a use case that informed keeping the two properties separate.
https://github.com/TBD54566975/tbdex/tree/main/specs/protocol#quote

**Comment by diehuxx** [comment]
Waiting until #206 is resolved to open PRs since this issue would create merge conflicts in the implementation changes. I have branches ready to PR as soon as #206 is done.

Spec change branch: https://github.com/TBD54566975/tbdex/compare/currency-199...quote-details-payment-instruction?expand=1
Javascript implementation change branch: https://github.com/TBD54566975/tbdex-js/compare/currency-199...quote-details?expand=1
Kotlin imeplementation change branch: https://github.com/TBD54566975/tbdex-kt/compare/currency-199...quote-details?expand=1

**Comment by diehuxx** [comment]
Ready for review.

Spec: https://github.com/TBD54566975/tbdex/pull/223
Javascript: https://github.com/TBD54566975/tbdex-js/pull/140
Kotlin: https://github.com/TBD54566975/tbdex-kt/pull/136
