### ISSUE TITLE
Consider removing `exchange_id` from submit message endpoints

### ISSUE THREAD

**Issue by phoebe-lew** [TBD54566975/tbdex#225]
Per https://github.com/TBD54566975/tbdex/pull/222#discussion_r1454286342

If we decide to, create corresponding issues in language implementation repos

**Comment by KendallWeihe** [comment]
I see a trend here towards two endpoints, one for resources and another for exchanges. 

1. `GET /resources`
2. `POST|PUT|GET /exchanges`

We have a requirement of making tbDEX protocol-agnostic (not married to HTTP), so anything we add to the HTTP layer is purely stylistic (AKA duplicative), with the intent of making it easier to comprehend. 

I think we should commit to one design choice or another b/c a middle ground is probably the most confusing. Either we implement the above two endpoints, without any additional HTTP parts (no query params, no path params, no headers, the bodies are 1:1 matches with message/resource types), or we duplicate information across the message/resource types and the HTTP parts with the intent of matching RESTful design patterns.

---

To contrast the above two endpoints with something more decorative:

- `GET /resources/offers`
- `POST /exchanges/rfq`
- `GET /exchanges/:id/quote`
- `POST /exchanges/:id/order`
- `GET /exchanged/:id/order-status`

**Comment by diehuxx** [comment]
> We have a requirement of making tbDEX protocol-agnostic (not married to HTTP)

Agreed

> so anything we add to the HTTP layer is purely stylistic (AKA duplicative), with the intent of making it easier to comprehend.

Not sure if I agree. Though the base protocol layer should be agnostic to HTTP, I understand the HTTP layer to be nearly as important as the base protocol layer because we are expecting the HTTP protocol to be a widely used way in production to send/receive TBDex protocol objects. It's possible I'm quibbling about semantics.

> I see a trend here towards two endpoints, one for resources and another for exchanges.
> without any additional HTTP parts (no query params, no path params, no headers, the bodies are 1:1 matches with message/resource types)

This approach is pretty restrictive. Without headers for authz on appropriate endpoints, authz becomes complicated. Without query params for `GET` endpoints, it becomes difficult to do simple filtering for past exchanges or resources. The restriction that bodies are 1:1 matches of message/resource types would preclude behavior like the `replyTo` field in the current submit RFQ request body.

> or we duplicate information across the message/resource types and the HTTP parts with the intent of matching RESTful design patterns.

I'm leaning more towards this. I like elements of the example you posted, but need to spend some more time thinking through what endpoint structure actually covers the use cases we have in mind.

**Comment by KendallWeihe** [comment]
Hey hey @diehuxx very thoughtful response! Ultimately I'll cede you're right, to me, primarily on the basis of your articulation that "`PUT` feels wrong" -- if feels wrong to me too (though I think that's a product of many years of software frameworks which didn't implement the HTTP spec to-the-T -- there's probably a lesson in that).

---

For the sake of brevity though I'll respond to some of the points.

> 1. URI accessibility

We could do `PUT /exchanges/:id` and then we'd have the subsequent `GET /exchanges/:id`

> E.g. Submitting an Order triggers the movement of money. If Alice submits an Order, then submits the same Order or an Order with the same exchangeId, that should (and does in our current implementations) return a 409 Conflict response.

I agree! This is idempotent, or at least my interpretation of idempotent. Idempotent is applicable to the result of the operation on the servers state, not the response status code. Subsequent requests returning 409 Conflict indicates idempotent behavior.

> the convention I have encountered is to use POST for creation and PUT for updates

Same. The weird nuance here is that `PUT /exchanges/:id` is a statement that Alice is actually "creating the exchange" whereafter then updating the PFI to notify them they have created the exchange. This actually gets to a philosophical matter which is the question of, _who owns the exchange?_ I mean, what does it even mean to "own" the exchange lol so I know it's wishy washy, but your words here...

> The client creates a TBDex message, and submits the message with potentially other data in the HTTP request, which creates a server "resource". The client does not create the server resource.

...leads me to interpret the PFI is the owner of the exchange because the implicit matter is that the "exchange is a server resource," but I would posit we should consider equal ownership among both parties. I'm imagining this is something we all could agree on so I'm not implying @diehuxx that you're taking a stance, only that the design decision of `PUT /exchanges/:id` (while initially counterintuitive) is reinforcing of the matter that Alice actually is an equal "owner." (Again wishy washy what it means to "own" so who cares we can move on lol)

**Comment by jiyoontbd** [comment]
i think the difference of opinions here is based on what constitutes `the resource` we're manipulating with each endpoint -

if one believes we're creating an `exchange`, then additions to an exchange (like rfq/etc) can seem like it should be a `PUT`, but if one believes we're creating `messages`, then additional messages can seem like it should be a `POST` ?

**Comment by mistermoe** [comment]
After some discussion, we've landed on the following proposal:



| Method | Endpoint              | Description                                                             |
|--------|-----------------------|-------------------------------------------------------------------------|
| POST   | `/exchanges`          | Used to send an RFQ aka _create_ an exchange.                           |
| PUT    | `/exchanges/:id`      | Used to add additional messages to a pre-existing exchange e.g. order, close |
| GET    | `/exchanges`          | Used to get exchanges                                                   |
| GET    | `/exchanges/:id`      | Used to get a single exchange                                           |


# Rationale
Technically both `/exchanges/{id}` and `/exchanges/{kind}` are surfacing duplicative information in the endpoint paths given that `kind` and `id` are both present in the message being sent. landed on the table above because it aligns more with RESTful conventions

**Comment by phoebe-lew** [comment]
^have not received any comments on the above proposal, so let's go ahead and follow what's in the table.
