### ISSUE TITLE
Split `Offering.payin/outMethod.kind` into specific fields

### ISSUE THREAD

**Issue by jiyoontbd** [TBD54566975/tbdex#233]
Currently, the example for `Offering.paymentMethod.kind` is something like 

![image](https://github.com/TBD54566975/tbdex/assets/118510103/bd3ab9de-bad5-4b44-85a7-d416c7d2e50d)

Other examples include `BANK_SomeBankName` or `MOMO_MPESA`

However, from the perspective of a wallet rendering the `kind`, we want the ability to break down the `type` of payment (i.e. bank, momo, etc) from the `provider` of payment (i.e. Chase, M-Pesa, etc). This is especially useful if a PFI has multiple payment method who has 1 `type` but many `providers` of that type, i.e. enabling MOMO via M-PESA or via MTN.

Exact names / how to narrow the definition of `kind` are to be determined.

**Comment by jiyoontbd** [comment]
@ethan-tbd would you be able to paste in a screenshot of the page were working on yesterday? 🙏

**Comment by ethan-tbd** [comment]
For additional context, in order for the Yellow Card PFI to process a [SelectedPaymentMethod](https://github.com/TBD54566975/tbdex/tree/main/specs/protocol#selectedpaymentmethod) in the RFQ, the client application is required to specify both a payment `type` (i.e. bank or mobile money) and the specific `provider` of that payment type (e.g. United Bank for Africa or M-Pesa). However, since our [offering only has a singular kind field](https://github.com/TBD54566975/tbdex/tree/main/specs/protocol#paymentmethod) to describe the payment method, Yellow Card is using prefixes in their offering `PaymentMethod.kind` field to denote the payment type and the corresponding suffix to denote the payment provider (e.g. `BANK_United Bank for Africa`, `MOMO_MPESA`).

![Simulator Screenshot - iPhone 15 Pro Max - 2024-02-07 at 08 51 40](https://github.com/TBD54566975/tbdex/assets/125412902/e080d085-77b0-43eb-b373-0fbcada5a4b6)
![Simulator Screenshot - iPhone 15 Pro Max - 2024-02-07 at 08 51 45](https://github.com/TBD54566975/tbdex/assets/125412902/3cb546f7-8b2e-4da1-9b2d-456f0ac21cde)

**Comment by mistermoe** [comment]
addressed by #261
