### ISSUE TITLE
Provide Enum of OrderStatus and Close status

### ISSUE THREAD

**Issue by angiejones** [TBD54566975/tbdex#256]
Can we provide a few enums for `message.data.orderStatus`  for `OrderStatus` and `message.data.reason` for `Close`? The method signatures don't have to change, so the respective properties can continue to be String, allowing PFIs to enter custom details there. But I'm thinking, right now, this is wide open. We're talking across borders, the Strings might not even be in English, so as a wallet app, I'm showing a Spanish string as a status update from the PFI because there's no enums or standards here.

**Comment by KendallWeihe** [comment]
We spoke about this at Office Hours, so re-articulating what was the strongest consensus. No need to implement status enums, for the time being, because we can bucket order execution into one of three statuses:

1. Pending/processing/executing (use whatever word ya want which means it's actively being executed)
2. Completed
3. Failed

And so, the mechanism for wallets to detect which state the order execution is within (so that the wallet GUI can display to the end user) is as such:

```
if Close does not exist: EXECUTING
else if Close.success == true: EXECUTED
else if Close.success == false: EXECUTION_FAILED
```

(I used consistent verbiage of "execute" across all three semantic buckets, just keeping you all on your toes 😄)

---

There is a broader question of how this plays out as things progress, but the above consensus seemed pragmatic for the time being.

**Comment by phoebe-lew** [comment]
Closing this because we will implement `Close.success` to distinguish between success/failures

**Comment by angiejones** [comment]
@phoebe-lew this is a different issue that's around random OrderStatus strings and offering a few standard ones.

**Comment by phoebe-lew** [comment]
@angiejones can you explain your use case vs Kendall's comment?

**Comment by angiejones** [comment]
> @angiejones can you explain your use case vs Kendall's comment?

I'm talking about `OrderStatus` which comes before the `Close` message. Specifically I'm talking about the Strings that PFIs are sending back to the Client

**Comment by KendallWeihe** [comment]
Terminology: for the sake of this ticket let's refer to two things 

1. `OrderStatus.status` is the value within the `OrderStatus` message
2. "Natural language OrderStatus" (AKA "NLO") is the value which is presented to the end user in the GUI

If I understood the consensus we came to is, there are two distinct matters, but feel free to challenge that as perhaps there's an argument to be made that this feature ought to be supported at the protocol-level (I believe the case against doing so is, the complexity of trying to solve this at the protocol-level is practically intractable).

The idea being that, the wallet will make the choice as to what language is presented to the user for the case of (what I defined as) "EXECUTING" and if will be able to do so based on the ruleset (re-pasting from comment above):

```
if Close does not exist: EXECUTING
else if Close.success == true: EXECUTED
else if Close.success == false: EXECUTION_FAILED
```
