### ISSUE TITLE
Include rate in `Quote` message

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/tbdex#330]

**Comment by jiyoontbd** [comment]
notes out of tbdex wg discussion
- use UNrounded rate as a top level field in `Quote` message

**Comment by nburgess48** [comment]
After further thought I agree it'd make sense to explicitly include a top level unrounded rate in the `Quote`. That said, I think this should be an Eng decision, since the relevant Regulatory requirements can all be met as-is:
1. The PFI must use the actual exchange rate when calculating total to recipient (not a rounded rate)
2. The Wallet rendering an Offering must disclose a rounded exchange rate to users
3. The Wallet rendering an Offerings must consistently disclose Offerings' details

During our mtg, I was incorrectly concerned about Req 3 being met if we include an explicit rate in the `Quote`. Since some PFIs might apply the rate to the `payin` amount after fees, and others to the `payin` amount before fees. But in those two scenarios the rate itself isn't changing, it's just how it's applied that's changing. And that difference is reflected in the `payout` amount that will be disclosed to users. All that said, I was wrong in my thinking during the meeting, and this proposal meets all of our requirements.
